### ISSUE TITLE
First Time Setup update?

### ISSUE THREAD

**Issue by w7sst** [w7sst/MorseRunner#270]
### Description
@scotthibbs 
Hi Scott, I was just wondering if you wanted to update the `Help | First Time Setup` menu pick?

![image](https://github.com/w7sst/MorseRunner/assets/106113737/6046291f-7abd-4f86-b310-1ab4a33e4d90)

The text is generated with the following code in Main.pas:
```
procedure TMainForm.FirstTime1Click(Sender: TObject);
const
    Msg='First Time?'#13 +
        'Welcome! This is the first time setup:'#13 +
        ''#13 +
        '1) Select the Contest you wish to operate.'#13 +
        '2) Type the exchange you wish to send.'#13 +
        '3) In the station section replace VE3NEA with your call.'#13 +
        '4) Select your CW Speed, Tone, and Bandwidth.'#13 +
        '5) Set Min/Max CW Receive speed using Settings menu.'#13 +
        '6) Under band conditions you can select any realistic hardships.'#13 +
        '7) Activity is the average amount of responses you want per CQ.'#13 +
        '    So if no one responds, you might get twice the number the'#13 +
        '    following time. This is a pile up trainer after all - have fun.'#13 +
        '8) Select the time limit you want to run the contest.'#13 +
        '9) The Run button has a drop down.'#13 +
        '    - Pile up - Hit Enter or F1 to call CQ to start. Get ready for pileups!'#13 +
        '    - Single Calls - Work one station at a time with no pileups.'#13 +
        ''#13 +
        'Please visit us or provide feedback at either:'#13 +
        '    - www.github.com/w7sst/MorseRunner/#readme'#13 +
        '    - https://groups.io/g/MorseRunnerCE';
begin
    Application.MessageBox(PChar(Msg),
      'First Time Setup',
      MB_OK or MB_ICONINFORMATION);
end;
```

Type up the new text in this issue and I can update the code. Tnx, Mike

**Comment by scotthibbs** [comment]
Sorry this didn't keep my formatting and indent for you. My 'Have Fun!'#13 + line should be justified (centered) for a better look.

**Comment by scotthibbs** [comment]
1. Yes, please change this to "Welcome to Morse" 
2. Exclamation works better

Sadly, the windows chime is needed to alert me when I'm clicking away from a modal window/element. This is actually very handy when I use three monitors on my desk (four monitors on my shack pc) to know I need to pay attention to a program somewhere else. Please also consider that the windows chime is associated with "something is wrong" or "something needs attention". It is not a happy sound to be sending users when everything is normal. I consider unnecessary beeps bad programming. I believe it is in Pascal because it predates Windows 95 and Windows 98 when the chime became the "your mouse has died a horrible death" sound. (IT Crowd theme song ending)   

If you want to blue circle thingy without a chime the MB_ICONEXCLAMATION will do. You can leave the unnecessary beep in if you want, at least I've made my case. :)

**Comment by w7sst** [comment]
I think I have found a way to use a different mechanism without the bell. I'll send you a build at some point so you can let me know if the annoying beep is gone. I don't get the noise here, so I don't know if I've fixe anything or not.

I'll make the changes and get this into code review.

Tnx, Mike

**Comment by w7sst** [comment]
I found a way to turn on my system sounds. I had turned them off when running digital modes with my laptop. So I can hear the annoying beep with the dialog. I'll try to find a way to eliminate it. I can now test your idea of removing/changing the icon.

**Comment by w7sst** [comment]
> "By changing MB_ICONINFORMATION to MB_ICONEXCLAMATION, you'll get an exclamation icon instead of an information icon, and thus, there won't be any beep sound accompanying the message box."

Well, both icons have a system sound associated with them.

When I remove the MB_ICONINFORMATION icon, there is no system sound and it will look like this ...
![image](https://github.com/w7sst/MorseRunner/assets/106113737/bddcd5b6-8637-405a-a6ad-ec82d240f135)

**Comment by w7sst** [comment]
Here is my final version. I have removed the icon (and the system beep) from both the `Help | About` and `Help | First Time` dialogs.

![image](https://github.com/w7sst/MorseRunner/assets/106113737/abaf5f2f-839e-4df7-a076-b4362bb445e2)
