### ISSUE TITLE
Menu Item: Help/About

### ISSUE THREAD

**Issue by scotthibbs** [w7sst/MorseRunner#60]
### Description

The Help menu About entry doesn't give an about. Currently it returns a "The contest is over" form with "Your score string is:" with the string to submit and several buttons to submit a score. (score submission form)

This Score submission form and the menu item "Score Submission" should be created and moved under the File menu. It needs to be reworked into a new submission process yet to be decided on. So when this is removed from "about", a new feature issue should be created so this isn't lost from our program. 

### Steps To Reproduce

1. The help menu
2. Click on About
3. Score submission is given instead of about.

#### Expected behavior

I'm thinking the top of our readme file or same as the splash screen should be returned. 

#### Actual Behavior

Score Submission form is opened. 

#### Reproduces how often

100% 

### Version information

  - Morse Runner version: [e.g. 1.68]
  - OS/Version: [e.g. Windows 10]

### Can you help?

Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [x ] Yes, I'm available to help test a solution to this problem.

**Comment by w7sst** [comment]
hi @scotthibbs,

I discovered in the code that the `Help > About...` menu pick had a commented-out line of code. When I remove the comment, we see the following MessageBox appears:
![image](https://user-images.githubusercontent.com/106113737/195512618-354a356c-9f0b-4a07-847d-6fa3098f7cee.png)

So, one easy fix for now will be to restore this dialog box and update it with our additional copyright information, updated name (`Morse Runner CE`), and add the current version number (`Version 1.81`) under `CONTEST SIMULATOR`. I would add the updated name to the MessageBox's title (e.g. `Morse Runner CE`).

For the score popup box that is currently showing with `Help > About...`, we could either
1. temporarily remove it until we get a new solution, or
2. add a new menu pick, say `About > Submit Score...`.

I don't like option 1 because bh1scw still allows you to send him your score string to be entered into the website. This leaves option 2 as a good way to go.

Second, what do you think of creating an email address, perhaps `morserunner@gmail.com`? Or we can direct them to our feedback/question page in our GitHub world.

Thoughts?

**Comment by scotthibbs** [comment]
I like the added submit score menu as well.

And for feedback let's offer both. Some may feel more at ease with email,
others the github feedback..

**Comment by BH1SCW** [comment]
Should we improve the score of submitting part?
 Do we need some way to register/login to avoid anonymously submitting？

**Comment by w7sst** [comment]
> Should we improve the score of submitting part? Do we need some way to register/login to avoid anonymously submitting？

Hi, thank you for contributing to the conversation.

Yes, absolutely. We would all like to see a solution to this. Scott has some ideas on this. We will want to track this in a separate issue.

Perhaps Scott or yourself can add this topic as Discussion topic so we can discuss this. Thank you for bringing this up.

**Comment by w7sst** [comment]
@scotthibbs ,
How does this work for an about box?
![image](https://user-images.githubusercontent.com/106113737/195528877-3301865d-6fcc-49c3-bbef-bde1705532b0.png)

Unfortunately, the URL is not a live link. We can improve this later; but for now, this might work.

thoughts?

**Comment by scotthibbs** [comment]
I like the about box! We can set up an issue to make it a live link for later. 

I'm also ok with Morse Runner CE.. however, I don't want to shorten it yet. Not many people know what CE stands for, and right now we want to emphasize the Community Edition aspect of our work.

**Comment by w7sst** [comment]
While restoring the About box, I discovered calls to:
- PopupScoreHST() - displays a string
- PopupScoreWpx() - displays a score submission tool

See Issue #57 for resolution on how to submit scores via the web. The above functions have been placed in a `57-menu-item-fileview-hi-score-web-page` feature branch and will be resolved when #57 is fixed.
